# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="e21208e7-7955-4394-aa7d-91ebca70ab86"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -fazlyev@phystech.ru
    on_success: never # default: change
    on_failure: always # default: always